project_id = "xasbgkggwnkvrceziaix"

[functions.mapbox-token]
verify_jwt = false

[functions.generate-park-description]
verify_jwt = false

[functions.vet-service]
verify_jwt = false

[functions.google-places]
verify_jwt = false

[functions.import-services]
verify_jwt = false

[functions.explore-assistant]
verify_jwt = false
