project_id = "xasbgkggwnkvrceziaix"

[functions.mapbox-token]
verify_jwt = false

[functions.generate-park-description]
verify_jwt = false

[functions.vet-service]
verify_jwt = false

[functions.google-places]
verify_jwt = false

[functions.geocode-parks]
verify_jwt = false
